apiVersion: apps/v1
kind: Deployment
metadata:
  name: emtl-data-loader-server
  namespace: production
  labels:
    app: emtl-data-loader-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: emtl-data-loader-server
  template:
    metadata:
      labels:
        app: emtl-data-loader-server
    spec:
      containers:
      - image: 10.152.14.66:30500/emtl-data-loader-server:latest
        name: emtl-data-loader-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: PYTHONPATH
          value: /app/src
        - name: PORT
          value: "8000"
        - name: ENVIRONMENT
          value: "production"
        volumeMounts:
          - mountPath: /app/src/emtl_server/retrievers/raw_data
            name: emtl-data-loader-server-raw-data-pvc
          - mountPath: /app/src/emtl_server/auth/keys
            name: emtl-data-loader-server-api-keys-pvc
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
      volumes:
        - name: emtl-data-loader-server-raw-data-pvc
          persistentVolumeClaim:
            claimName: emtl-data-loader-server-raw-data-pvc
        - name: emtl-data-loader-server-api-keys-pvc
          persistentVolumeClaim:
            claimName: emtl-data-loader-server-api-keys-pvc