apiVersion: v1
kind: Service
metadata:
  name: emtl-data-loader-server
  namespace: production
  labels:
    app: emtl-data-loader-server
spec:
  type: ClusterIP
  selector:
    app: emtl-data-loader-server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emtl-data-loader-server-ingress
  namespace: production
  labels:
    app: emtl-data-loader-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: emtl-data-loader-server.10.152.14.66.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emtl-data-loader-server
            port:
              number: 8000